# Generated by Django 4.2.4 on 2023-09-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="discrimination",
            field=models.CharField(
                choices=[("female", "여성"), ("male", "남성")], max_length=13
            ),
        ),
    ]
