# Generated by Django 4.2.4 on 2023-11-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
