# Generated by Django 4.2.4 on 2023-11-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_age_user_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.DateField(null=True),
        ),
    ]
