# Generated by Django 4.2.4 on 2023-11-05 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="friend",
            field=models.ManyToManyField(
                related_name="friends", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
