# Generated by Django 4.2.4 on 2023-11-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="dating",
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="deny",
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="hobby",
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="more",
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="prefer",
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
