# Generated by Django 4.2.4 on 2023-11-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_profile_dating_profile_deny_profile_hobby_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="drive",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "면허 없음"), (1, "면허 있음"), (2, "차량 보유")],
                null=True,
            ),
        ),
    ]
