# Generated by Django 4.2.4 on 2023-11-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_profile_drive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="drink",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "안마셔요"), (1, "아주 가끔"), (2, "가끔"), (3, "자주")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="job",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="policy",
            field=models.IntegerField(
                blank=True, choices=[(0, "무관심"), (-1, "진보"), (1, "보수")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="religion",
            field=models.IntegerField(
                blank=True,
                choices=[
                    ("0", "무관심"),
                    ("1", "불교"),
                    ("2", "천주교"),
                    ("3", "기독교"),
                    ("4", "기타"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="school",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "고등학교 졸업"), (1, "전문대 졸업"), (2, "대학교 졸업"), (3, "대학원 졸업")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="smoke",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "-"), (1, "금연"), (2, "전자담배"), (3, "담배")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="weight",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "마른"),
                    (1, "슬림한"),
                    (2, "보통"),
                    (3, "탄탄한"),
                    (4, "통통한"),
                    (5, "뚱뚱한"),
                ],
                null=True,
            ),
        ),
    ]
