# Generated by Django 4.2.4 on 2023-11-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_alter_profile_policy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="religion",
            field=models.IntegerField(
                choices=[(0, "무관심"), (1, "불교"), (2, "천주교"), (3, "기독교"), (4, "기타")],
                null=True,
            ),
        ),
    ]
