# Generated by Django 4.2.4 on 2023-11-12 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_card_evaluate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="evaluate",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(5)],
            ),
        ),
    ]
