# Generated by Django 4.2.4 on 2023-11-15 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_alter_card_evaluate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
