# Generated by Django 4.2.4 on 2023-11-01 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="descriptions",
            field=models.ManyToManyField(
                related_name="descriptions", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
