# Generated by Django 4.2.4 on 2023-11-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
        ("meetings", "0003_meeting_invisible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="descriptions",
            field=models.ManyToManyField(
                related_name="meetings", to="payments.payment"
            ),
        ),
    ]
