# Generated by Django 4.2.4 on 2023-11-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
        ("meetings", "0004_alter_meeting_descriptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="descriptions",
            field=models.ManyToManyField(
                blank=True, related_name="meetings", to="payments.payment"
            ),
        ),
    ]
