# Generated by Django 4.2.4 on 2023-10-31 07:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chats", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="dislikes",
            field=models.ManyToManyField(
                related_name="dislikes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="likes",
            field=models.ManyToManyField(
                related_name="likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
